#!/bin/bash
#                 _            _             _
#      __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_
#     / _` | | | | __/ _ \/ __| __/ _` | '__| __|
#    | (_| | |_| | || (_) \__ \ || (_| | |  | |_
#     \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|

# Load .Xresources
xrdb ~/.Xresources
# Wallpaper
if [ "$HOSTNAME" == "pc" ];then
	feh --bg-fill --randomize /home/samedamci/.config/wallpapers/1920x1080/ &
elif [ "$HOSTNAME" == "laptop" ];then
	feh --bg-fill --randomize /home/samedamci/.config/wallpapers/1366x768/ &
fi

# Polybar
# killall -q polybar
# while pgrep -u $UID -x polybar >/dev/null; do killall -q polybar; done
# polybar polybarexe &
# sxhkd
killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do killall -q sxhkd; done
sxhkd &
# Dunst
killall -q dunst
while pgrep -u $UID -x dunst >/dev/null; do killall -q dunst; done
dunst &
# Picom
killall -q picom
while pgrep -u $UID -x picom >/dev/null; do killall -q picom; done
picom &

# Set keyboard layout & key swaping
setxkbmap -layout 'pl' -option caps:swapescape &
# Cursor
xsetroot -cursor_name left_ptr & # change the cursor shape from "x" to normal
xsetroot -name " samedamci "

# Not reload
[[ -z $(pgrep udiskie) ]] && udiskie &
[[ -z $(pgrep clipmenud) ]] && clipmenud &
[[ -z $(pgrep mpd) ]] && mpd &
[[ -z $(pgrep dunst) ]] && dunst &
[[ -z $(pgrep syncthing) ]] && syncthing -no-browser &
telegram-desktop &

~/.scripts/dwmbar &

# Welcome notify
dunstify "Hello ${USER}!"
