#!/bin/bash
#                 _            _             _
#      __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_
#     / _` | | | | __/ _ \/ __| __/ _` | '__| __|
#    | (_| | |_| | || (_) \__ \ || (_| | |  | |_
#     \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|

# Load .Xresources
xrdb ~/.Xresources
# Wallpaper
feh --bg-fill --randomize /home/samedamci/.config/wallpapers/1920x1080/ &

# Polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar polybarexe &
# Polybar
killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
sxhkd &
# Dunst
killall -q dunst
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done
dunst &
# Picom
killall -q picom
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom &

# Set keyboard layout & key swaping
setxkbmap -layout 'pl' -option caps:swapescape &
# Cursor
xsetroot -cursor_name left_ptr & # change the cursor shape from "x" to normal

# Not reload
[[ -z $(pgrep udiskie) ]] && udiskie &
[[ -z $(pgrep clipmenud) ]] && clipmenud &
[[ -z $(pgrep mpd) ]] && mpd &
[[ -z $(pgrep dunst) ]] && dunst &
telegram-desktop &

# Welcome notify
dunstify "Hello ${USER}!"
