#!/usr/bin/env sh

echo "Adding configs to dotfiles repo..."

cd ~
cp .zshrc .Xresources .profile .shellrc .bashrc .zprofile .bash_profile .local/share/TelegramDesktop/tdata/shortcuts-custom.json ~/Dotfiles/botfiles/ &>/dev/null
cd ~/.scripts/
cp * ~/Dotfiles/botfiles/.scripts/ &>/dev/null
cd ~/.config/

if [ "$HOSTNAME" = "pc" ]; then
	cat sxhkd/sxhkdrc > sxhkd/sxhkdrc.pc	
	cat polybar/config > polybar/config.pc	
elif [ "$HOSTNAME" = "laptop" ]; then
	cat sxhkd/sxhkdrc > sxhkd/sxhkdrc.laptop	
	cat polybar/config > polybar/config.laptop	
fi

cp -r flake8 mimeapps.list bspwm dconf dunst gtk-3.0 gtk-2.0 homepage mpd ncmpcpp neofetch nvim picom polybar qutebrowser ranger rofi sxhkd vifm vis vlc wallpapers yay zsh ~/Dotfiles/botfiles/.config/ &>/dev/null
cd ~/Dotfiles/botfiles/.config/
rm -rf nvim/bundle zsh/plugins mpd/database zsh/history mpd/mpd.log mpd/pid mpd/state mpd/sticker.sql vis/vis.log ncmpcpp/lyrics sxhkd/sxhkdrc polybar/config vifm/vifminfo

echo "Done."
