#!/bin/zsh

source "$HOME/.profile"

# Aliases
alias \
	v='nvim' \
  vi='nvim' \
  vim='nvim' \
  suvi='sudo -E nvim'

alias \
	l='ls' \
  ll='ls -l' \
	la='ls -a' \
	lal='ls -al'

alias \
	owo='pacman' \
  sowo='sudo pacman' \
  yay='yay --editmenu --nodiffmenu --save'

alias \
	btw='git --git-dir=$HOME/dev/botfiles/ --work-tree=$HOME' \
  ga='git add' \
  gc='git commit -S' \
  gp='git push' \
  gpom='git push origin master' \
  gch='git checkout' \
  gl='git log' \
  gpu='git pull' \
  gs='git status' \
  grm='git rm -f' \
  gi='git init'

alias \
	s='sudo ' \
	sudo='sudo '

fdir() { cd "$(find "$HOME" -type d | fzf --layout reverse --height 25)"; }
alias \
	scr='cd ~/.local/bin/scripts' \
	cfg='cd ~/.config/' \
	crn='cd ~/.local/bin/cron' \
	cd..='cd ..'

alias copy='xclip -sel clip'

# Commands Colors
alias ls='ls --color=auto' \
	ip='grc ip' \
	ping='grc ping' \
	ps='grc ps'
export SUDO_PROMPT="$(printf "\033[0;31m")[ sudo ]$(printf "\033[0m"): "

man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    # LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

export LESS=-R
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin blink
export LESS_TERMCAP_md=$'\E[1;36m'     # begin bold
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

# vim: ft=sh
