#!/bin/sh
#     _
#    | |__  ___ _ ____      ___ __ ___
#    | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
#    | |_) \__ \ |_) \ V  V /| | | | | |
#    |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#              |_|

#~~~~~~~~~~~~~~~~
# WINDOW MANAGER
#~~~~~~~~~~~~~~~~
bspc monitor -d one two three four five six seven eight nine ten
bspc desktop -f 1

BOR_UF=$(echo $(xrdb -query | awk '/\*.border_unfocused/ { printf $2 } '))
BOR_F=$(echo $(xrdb -query | awk '/\*.border_focused/ { printf $2 } '))

bspc config border_width         1
bspc config window_gap          3
bspc config normal_border_color "$BOR_UF"
bspc config focused_border_color "$BOR_F"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#~~~~~~~~~~~~
# APPS RULES
#~~~~~~~~~~~~
bspc rule -a qutebrowser desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a TelegramDesktop desktop='^4'

#~~~~~~~~~~~
# AUTOSTART  
#~~~~~~~~~~~
$SCRD/autostart &


