#!/bin/sh
#     _
#    | |__  ___ _ ____      ___ __ ___
#    | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
#    | |_) \__ \ |_) \ V  V /| | | | | |
#    |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#              |_|

#~~~~~~~~~~~~~~~~
# WINDOW MANAGER
#~~~~~~~~~~~~~~~~
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#~~~~~~~~~~~~
# APPS RULES
#~~~~~~~~~~~~
bspc rule -a qutebrowser desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a TelegramDesktop desktop='^4'

#~~~~~~~~~~~
# AUTOSTART  
#~~~~~~~~~~~
${HOME}/.config/autostart/autostart.sh &


